name: Publish reverse-proxy Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'reverse-proxy/*'
    tags:
      - 'reverse-proxy-*'

jobs:
  reverse-proxy:
    name: Publish reverse-proxy Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish reverse-proxy Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: offspot/reverse-proxy
          on-master: dev
          build-args:
            VERSION={tag}
          tag-pattern: /^reverse-proxy-([0-9.]+)$/
          restrict-to: offspot/container-images
          platforms: |
            linux/amd64
            linux/arm64
          context: reverse-proxy
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
