name: Publish file-manager Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'file-manager/*'
    tags:
      - 'file-manager-*'

jobs:
  file-manager:
    name: Publish file-manager Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish file-manager Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: offspot/file-manager
          on-master: dev
          build-args:
            VERSION={tag}
          tag-pattern: /^file-manager-([0-9.]+)$/
          restrict-to: offspot/container-images
          platforms: |
            linux/amd64
            linux/arm64
          context: file-manager
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
