name: Publish magoe Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'magoe/*'
    tags:
      - 'magoe-*'

jobs:
  magoe:
    name: Publish magoe Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish magoe Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: offspot/magoe
          on-master: dev
          build-args:
            VERSION={tag}
          tag-pattern: /^magoe-([0-9.]+)$/
          restrict-to: offspot/container-images
          platforms: |
            linux/amd64
            linux/arm64
          context: magoe
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
