name: Publish captive-portal Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'captive-portal/*'
    tags:
      - 'captive-portal-*'

jobs:
  captive-portal:
    name: Publish captive-portal Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish captive-portal Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: offspot/captive-portal
          on-master: dev
          build-args:
            VERSION={tag}
          tag-pattern: /^captive-portal-([0-9.]+)$/
          restrict-to: offspot/container-images
          platforms: |
            linux/amd64
            linux/arm64
          context: captive-portal
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
